/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseMap: typeof import('./src/components/BaseMap.vue')['default']
    BufferRangeSelector: typeof import('./src/components/BufferRangeSelector.vue')['default']
    Display: typeof import('./src/components/Display.vue')['default']
    GXStatistic: typeof import('./src/components/GXStatistic.vue')['default']
    Layer: typeof import('./src/components/Layer.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    Query: typeof import('./src/components/Query.vue')['default']
    QueryButtons: typeof import('./src/components/QueryComponents/QueryButtons.vue')['default']
    QueryConditions: typeof import('./src/components/QueryComponents/QueryConditions.vue')['default']
    QueryContianer: typeof import('./src/components/QueryComponents/QueryContianer.vue')['default']
    QueryResultDialog: typeof import('./src/components/QueryComponents/QueryResultDialog.vue')['default']
    QuerySpace: typeof import('./src/components/QueryComponents/QuerySpace.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Statistics: typeof import('./src/components/Statistics.vue')['default']
    TJStatistic: typeof import('./src/components/TJStatistic.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
